server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codetool?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    cache: false
    mode: HTML
